services:
  postgres:
    image: postgis/postgis:16-master
    container_name: PostgresDB
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-petradar}
      - POSTGRES_USER=${DB_USER:-postgres}
    volumes:
      - postgres_data_db:/var/lib/postgresql/data

volumes:
  postgres_data_db: